Fix gradle javadoc build with Java 7.
This fixes the sdk build error with Java 7:
Error: ## Unknown source 'sdkstats' to copy in 'sdk/eclipse/plugins/com.android.ide.eclipse.base/libs'
make: *** [out/host/darwin-x86/obj/EXECUTABLES/monitor_intermediates/monitor]    Error 1

Bug: 8992787
Change-Id: If57a36cd97f5303f8fdd376a6cdbe58759e09ca9
(cherry picked from commit 7c1a2d3e072391e8795f3ab46728e48682e92e07)