Revert "More friendly error messages for StableApiTest"
When updating to Gradle 4.3 the test consistently fail with:

java.lang.IllegalAccessError: com/google/common/reflect/Element
	at com.android.build.api.StableApiTest.lambda$getApiElements$8(StableApiTest.java:163)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)


java.lang.IllegalAccessError: tried to access class com.google.common.reflect.Element from class com.android.build.api.StableApiTest
	at com.android.build.api.StableApiTest.lambda$getApiElements$8(StableApiTest.java:163)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)

With the revert, the tests pass.

This reverts commit 5f63f11a65fdcdf7c7da4b6e3425e8af730dbfac.

Change-Id: I526fc56dc6bc78c3348594d98f2b36eecbb1fdf8