Fix the rendering issue with the Primary/Detail template
- Added tools:layout to indicate which fragment needs to be drawn in the
visual editor

- Removed the FAB in the activityMainXml.
  Because the FAB should be inside a fragment in this template's case.
  Also IllegalStateException is thrown from the FAB as follows.
  java.lang.IllegalStateException: An anchor may not be changed after CoordinatorLayout measurement begins before layout is complete.

- Change the layout_anchor of the FAB in the fragmentItemDetailXml
  The layout_anchor needs to specify a direct descendant of the
  CoordinatorLayout

- Replace fragment tag with FragmentContainerView
  Also changed the code to get NavController as documented at
  https://developer.android.com/guide/navigation/navigation-getting-started#java

Bug: 172966600
Test: TemplateTest, Manually created PrimaryDetail Activity for both
Java and Kotlin

Change-Id: Ic5d6a758e1f713074fcd36a7c8d22b97b0ff581c