Fix groovyc dependencies
Groovy 2.3 requires Ant:
https://stackoverflow.com/questions/23813634/gradle-build-with-groovy-2-3-throws-noclassdeffounderror-due-to-missing-dependen

Test: N/A
Change-Id: Ie0d47e4294ecfff98a67f4023828978de92b7999