Revert "Fix tests that needs files from resources in jars"
Build errors:
VmTraceParserTest.java:351:
cannot find symbol
return TestResources.getFile(getClass(), path);

This reverts commit 2e87e31944837d43a5f8aca157ec9ded88d09934.

Change-Id: I4b7e4a18745347ed0f4f76dc3818a4b32c1d1833