Fix bazel target argument
Using "${TARGETS}" with quotes would cause bazel to fail with the
following error:
ERROR: Skipping '//tools/... -//tools/adt/idea/studio/...': Invalid
package name 'tools/... -//tools/adt/idea/studio': package names may not
contain '//' path separators

Test: Ran script locally
Bug: 188672179
Change-Id: I65a94beb0c0e1b91f585a1cf85460916207ce2d1